spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    user: root
    password: root
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: travel
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.travelers.gotravelserver.domain
  configuration:
    map-underscore-to-camel-case: true


